### ISSUE TITLE
Odd values possible with SnapToGrid enabled

### ISSUE THREAD

**Issue by Guddler** [Phillrb/VectorGen#2]
When snap to grid is enabled, all points should be in multiples of 10. Certain points are off by one though:

For both X & Y: -51 & +29 & +109 are possible.

**Comment by Phillrb** [comment]
Addressed in latest submit: https://github.com/Phillrb/VectorGen/commit/7af41da93e6d38fba3dfa0cc5c0a7412af5c866d
